# Generated by Django 2.0.1 on 2018-01-12 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaldata',
            name='market_cap_ranking',
            field=models.IntegerField(default=0),
        ),
    ]
